### ISSUE TITLE
Deployment Workflow needs secret

### ISSUE THREAD

**Issue by philnorc** [Greenstand/greenstand-documentation#15]
I created a workflow "Deploy website"
It needs a password stored in this repository as a secret.
I don't have the power to do that.
I need a secret named philftp 

The workflow will copy files from /greenorg/docs/* to greenstand.org/docs 
( but first it is configured to copy to & from a test directory: /greenorg/docs/ttxt/ )
via the FTP server at 156.67.236.37 and my username p366052f3
The workflow cannot use FTPS, but neither can that FTP server.
The workflow script relies an a library from 
https://github.com/SamKirkland/ftp-deploy

I tested the workflow from my fork of this repo:
https://github.com/philnorc/greenstand-documentation
and deployed to philnorcross.com
All worked well.

**Comment by dadiorchen** [comment]
@philnorc you don't have the permission on this repo to open the `settings` tab right? If you just need a secret, I can help to add one, you can send the password to me I think.

**Comment by philnorc** [comment]
I tested the deployment. Works good.

**Comment by philnorc** [comment]
I still have a problem. The deployment workflow, main.yaml, 
needs to differ between here at the Greenstand repo and at the fork on github.com/philnorc
.gitignore includes
```
.github
*/main.yaml
.github/workflows/main.yaml
```
Nonetheless when complete a pull request and merge the fork into Greenstand,
the main.yaml changes to sync with the fork. 
That's bad. Now I've lost the name of the secret and can't fix main.yaml

**Comment by philnorc** [comment]
OK. 
I fixed main.yaml
I got the name of the secret from the commit that created it.

**Comment by philnorc** [comment]
But the problem remains.
I sync my fork by merging Greenstand into philnorc
Now philnorc/.github/workflows/main.yaml has bad
server, user, and password parameters that it got from Greenstand/.github/workflows/main.yaml

**Comment by dadiorchen** [comment]
I am not sure I knew your case clearly, my way to do the work is: everytime, I will checkout the code from greenstand/master, then create a new branch for the new feature/bugFixing, then raise a PR, when the PR merged, I remove the branch.
If there are new code merged in greenstand/master, and I want to up to date, then I do `git rebase` if failed, then I do `git merge greenstand/master`. 
Hope this is helpful.

**Comment by philnorc** [comment]
OK. I get it, I think. Thanks.
