### ISSUE TITLE
Consolidate Documentation Repositories

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand-documentation#18]
We currently have 3 different dedicated documentation repositories and the development overview repository. 

1. Can we consolidate them all into the ~~Development Overview~~ [**Greenstand Overview**](https://github.com/Greenstand/Greenstand-Overview) Repository, (I understand this may not be possible due to the complex nature of our needs) 
2. Can we delete the other two documentation repositories.

**Comment by dadiorchen** [comment]
I think this one is a special case, it is a repo for saving the webpage, and deploy to the doc website of Greenstand.

**Comment by philnorc** [comment]
In this repository there is one folder, 'greenorg/docs', that holds the files that go to the website, 'greenstand.org/docs.  Anything outside that folder DOES NOT go to the website. 

If we are going to put all the documentation on github, and index it in a README on github, then we can abandon this repo. If we want to put any documentation on greenstand.org, then I urge that we maintain this repo.

**Comment by philnorc** [comment]
if you like, we can use this repo's README to index and link to documentation on any and all other documentation, whether its on github, greenstand.org, gitbook, or anywhere else on the net.

**Comment by philnorc** [comment]
But..
While such an index may serve software developers well. Growers and funders will be disoriented. They will expect normal web pages at greenstand.org.

**Comment by philnorc** [comment]
For converting MD to HTML, I'm studying a javascript tool named Showdown (https://github.com/showdownjs/showdown) It seems we can run it client side, to convert MD files at users machines after they request a file. Or we can run it on a nodeJS server, perhaps as part of the publishing workflow. Who? How? would we run a nodeJS server for that purpose?

**Comment by Davidezrajay** [comment]
I've spent some time looking at Github pages, which might be an easy option.

**Comment by philnorc** [comment]
OK. I second the motion to write it all in MD on github, in the 
Greenstand-Overview repository (https://github.com/Greenstand/Greenstand-Overview)
That's quick and easy. It will serve developers.

Abandon the documentation web sites and the other documentation related repositories.
- (https://greenstand.org/docs)
- (https://greenstand.org/devbox)
- (https://github.com/Greenstand/greenstand-documentation)
- (https://github.com/Greenstand/microservices-documentation)
- (https://github.com/Greenstand/meta-documentation)
- (https://github.com/Greenstand/system-design-docs)

(That assumes that the reference to "the Development Overview Repository" at the start of this issue means to say "Greenstand-Overview". I cannot find any "Development Overview.")

Before deleting greenstand-documentation and meta-documentation, let's preserve their useful parts by moving them to Greenstand-Overview.
That is:
- https://github.com/Greenstand/meta-documentation/blob/main/README.md
- https://greenstand.org/docs/user-guides/earningshow.php
- https://greenstand.org/docs/user-guides/earningsref.php
- https://greenstand.org/docs/user-guides/walletapihow.php
- https://greenstand.org/docs/user-guides/walletapiref.php

If someone will confirm that they are not outdated, I will convert the *.php files to *.md so that they are more readable on github.

**Comment by dadiorchen** [comment]
@philnorc these are wonderful! Thank you for you work!

**Comment by philnorc** [comment]
Thanks. I think. What exactly do you mean by "these"?

**Comment by philnorc** [comment]
And what of all the documentation on gitbook
https://app.gitbook.com/o/-MXNadx4i6aOZ12XcStA/home
Do we want to move that to github *.md files as well?

**Comment by Davidezrajay** [comment]
> But.. While such an index may serve software developers well. Growers and funders will be disoriented. They will expect normal web pages at greenstand.org.

There needs to be a forward facing element to these documents. This can be done a number of ways: via this website, Github pages, Gitbook, etc.

Keeping as much as possible in MD is great (and we can deal with the YMAL some other way) 

- Gitbook: lots of permission and organizational issues that can be solved by feeding it from Github, rather than entering the text via Gitbook)
- Github pages: flexible, a little work to set up but 
- This website: not a bad idea, gut feeling is that PHP might not be the way to go.

**Comment by Davidezrajay** [comment]
Is the following order of operations suitable?  

1.  Index all documentation in file in Github Greenstand_Overview (including wiki's, repository readmes, and the wonderful list above. 
2.  Create a solid strategy for serving / organizing the information
3. Setup (or optimize the current) the front end facing elements.
4. Start a review and pull all documentation off of Gitbook, and the above user guides.

**Comment by philnorc** [comment]
There are also documentation files at 
(https://docs.greenstand.org/engineering/)
(https://docs.greenstand.org/web-map/)

**Comment by philnorc** [comment]
[For new and improved 2nd thoughts, see the comment after next.]

We need to move stuff OUT of documentation as well as into it.

We have proposed centralizing all documentation in the [Greenstand-Overview](Greenstand-Overview repository (https://github.com/Greenstand/Greenstand-Overview) repo. 

But that repo now contains pieces that do not belong in documentation and should be moved out.
EIther that or we give documentation a whole new repo all to itself.

There's the Bilaws and the Code of Conduct, for example. But esp. look at the list of [issues](https://github.com/Greenstand/Greenstand-Overview/issues).

**Comment by philnorc** [comment]
[For new and improved 2nd thoughts, see the next comment]

If the repo named "Greenstand Overview" is to become the one central source for documentation, please avoid confusion by renaming Documentation.md to something more specific, "Documentation-Grant-App" perhaps. 
https://github.com/Greenstand/Greenstand-Overview/blob/master/Documentation.md

Also, consider renaming this repo here to, say, "greenstand-docs-old";
then renaming Greenstand-Overview to Greenstand-Documentation.

**Comment by philnorc** [comment]
I have a better idea:
- Keep Greenstand-Overview as is.
- Continue to use this repo here, greenstand-documentation, as the consolidated documentation repo.
- I will remove from greenstand documentation the files we no longer want: 
  *.php files, node.js server files, *.js files for the apache server.

That will be easier than cleaning up Greenstand-Overview. 
And "greenstand-documentation" is a more accurate name for what we're doing.
And I have sufficient access to start the work now.

See the pull request I just submitted.
I won't accept the pull until you OK, Ezra.

**Comment by Davidezrajay** [comment]
@philnorc let's go with the last idea - use Greenstand-Documentation repository to consolidate. 

Then how would you like to display it?

**Comment by philnorc** [comment]
@Davidezrajay I thought we decided to display the documentation in the greenstand-documentation repo, in *.md files. 

In a github repo is the only way I know of to display *.md files. 

If you put *.md files on a web site, like greenstand.org, without software that converts them to HTML, they look like this: https://raw.githubusercontent.com/Greenstand/Greenstand-Overview/master/Documentation.md

**Comment by Davidezrajay** [comment]
> @Davidezrajay I thought we decided to display the documentation in the greenstand-documentation repo, in *.md files.
> 
> In a github repo is the only way I know of to display *.md files.
> 
> If you put *.md files on a web site, like greenstand.org, without software that converts them to HTML, they look like this: https://raw.githubusercontent.com/Greenstand/Greenstand-Overview/master/Documentation.md

We could use Github pages and they add a customized theme to the docs using something like this https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll

**Comment by philnorc** [comment]
How are Github pages simpler than what we did before? We had a workflow in this repo that published this repo's files to https://greenstand.org/docs/ 
That used the customized theme that we have already built.

**Comment by philnorc** [comment]
Ezra,
You ask me to write things for you,
but nobody reads what I produce.

You ask me how to publish documentation,
so I build something for you.
You respond, "Nah. Let's do it a different way."

I go to meetings hoping for decisions
about how to help people who use your software.
Instead we talk in repetitive circles about how
to train developers.

I'm done with your organization.
You don't pay me enough for this useless aggravation.

Phil Norcross

**Comment by Davidezrajay** [comment]
Dear @philnorc,

Like a precentor with an unsingable song
Frustrated with a note in a verse too long.
The problems didn't just dissolve with time. 

The solutions evolved. 

We leaders with cordial greetings, meet in meetings.
I, people, planters, orgs, and everyone struggling to 
Navigate, Comprehend, and Stand on what is "a Greenstand?"

Time and again an informed decision
In need of revision after revision.
Who was the leader without our answer?

It was not such a simple task.

Publish ALL and any documentation in a way 
That ANYONE can easily find and edit any day
Can we figure it out this or do we try a different...

I let us go around in circles.

Now led by a simple understanding 
I, a volunteer, shed off useless aggravation
to finish the new documentation organization.

I deeply regret having let to your frustration
Yet in admiration, I delight for what we solved is live.
You set the notes in a refrain that will remain and thrive. 

Thank you - for all your hard work and dedication to the project - you will be missed. 
Ezra
