### ISSUE TITLE
Define where to keep the documentation "index"

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand-documentation#19]
As we move forward to make an index of the scattered documentation, where should that live? 
I am inclined to add it to the development overview, repo, but will go with what @philnorc chooses.

**Comment by philnorc** [comment]
Thank you for your confidence, Ezra. But please allow for my outdated knowledge of what's available off the shelf.

**Comment by philnorc** [comment]
1. I understood we are aiming to create documentation for growers, funding organizations, and developers. An index in the development overview can be created faster, but will only serve developers.

**Comment by philnorc** [comment]
Let's resolve this issue. Issue #18 covers the same ground.
