### ISSUE TITLE
Use safe way to handle the secret here

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/greenstand-documentation#20]
https://github.com/Greenstand/greenstand-documentation/blob/c580ea50cbbea8af5a5e9a48c1dc4b9aa1047a51/.github/workflows/main.yaml#L17-L18

**Comment by philnorc** [comment]
Maybe this solves our problem: Github newly offers the power to precisely control access to various parts of a repo, including its secrets. See "Fine-grained personal access tokens" (https://github.com/settings/tokens?type=beta)

**Comment by dadiorchen** [comment]
@philnorc we have done some similar thing in other repos, using the Github Action secret, like this:
https://github.com/Greenstand/treetracker-admin-client/blob/ad51cef558557dcd59a2fa9b61c3814a4f75f364/.github/workflows/deploy.yaml#L146-L151

Our cloud team can help set up this, @emmanue

**Comment by philnorc** [comment]
The secret discussed here is no longer an issue. See issue 18 of this repo.

**Comment by philnorc** [comment]
The secret discussed here is no longer an issue. The workflow in question has been deleted.
