### ISSUE TITLE
Define Workflow for edit and publish of documentation

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/greenstand-documentation#28]
We have done a lot of work here. Github solves the edit side of this equation. 

We do not have a publish option yet. Github pages could be a great option. If we decide to go this way, we will need someone to set up github pages.

**Comment by pranavkparti** [comment]
We have finalized on Gitbook as the platform to host documentation. It can be synced with Github so the edit and publish options are both taken care of.

**Comment by dadiorchen** [comment]
This is awesome!

**Comment by dadiorchen** [comment]
Where can I find the guide for this? to sync to github?
