### ISSUE TITLE
Extend Wallet API with how to get information on the capture from the APi result 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/greenstand-documentation#32]
Part of the response is the following below 

```
"links": {
        "capture": "/webmap/tree?uuid=c77bb5fb-a05f-4dc3-9c23-d18fd3b69415"
    }
```
    
    
  This is one of the key features since this link provides the actual info on the capture that is represented by the token. 
  
`  https://prod-k8s.treetracker.org/webmap/tree?uuid=c77bb5fb-a05f-4dc3-9c23-d18fd3b69415`
  
This needs to be a part of the documentation. The resulting json when making this call carries all info that can then be used to build customized maps etc. 
  
Additional operational info: Integrators have had trouble making this call to pull information due to performance issues so we recommend to limit the amounts of calls and get this info in increments.

**Comment by philnorc** [comment]
Part of the response to what?

The bit of data you cite is in the documenation.

https://greenstand.org/docs/user-guides/walletapiref.php#getTokens
https://greenstand.org/docs/user-guides/walletapiref.php#getToken
\
If you don't have time to read documentation, I don't have time to write it.
