### ISSUE TITLE
Create a documentation for treetracker app testing for iOS

### ISSUE THREAD

**Issue by CorrWu** [Greenstand/greenstand-documentation#43]
Create a iOS version of this doc: https://github.com/Greenstand/treetracker-android/wiki/Treetracker-App-Testing-Instructions

1. Request an email 'invitation' from iOS Team to the testing environment
2. Download the TestFlight app on an iPhone
3. Press the 'Redeem' button on the top right corner and enter the invitation code from the email
4. Download the corresponding build on the phone
5. Sign up and login to the Treetracker testing app
6. Check ability to change users
7. Use app to capture image and record (Note: The app has a block for GPS accuracy. The user should be able to get GPS reception, "add a tree." Take a photo and upload the image.)
    - time per capture
    - any bugs
    - any unclear UX/UI
8. Sync data
9. Confirm data reaches the cloud by:
    - checking that the images should appear on the map at test.treetracker.org 
    - logging into the Tree Tracker Admin URL, https://test-admin.treetracker.org/
      - username: admin
      - password: ZwovDoOxCo
10. You can submit any defects/suggestions here under the Issues tab. https://github.com/Greenstand/treetracker-ios
11. If all checks ok, please report to the iOS Team

**Comment by CorrWu** [comment]
1. Request an email 'invitation' from iOS Team to the testing environment
2. Download the TestFlight app on an iPhone
3. Press the 'Redeem' button on the top right corner and enter the invitation code from the email
4. Download the corresponding build on the phone
5. Sign up and login to the Treetracker testing app
6. Check ability to change users
7. Use app to capture image and record (Note: The app has a block for GPS accuracy. The user should be able to get GPS reception, "add a tree." Take a photo and upload the image.)
  - time per capture
  - any bugs
  - any unclear UX/UI
8. Sync data
9. Confirm data reaches the cloud by:
  - checking that the images should appear on the map at test.treetracker.org 
  - logging into the Tree Tracker Admin URL, https://test-admin.treetracker.org/
      - username: admin
      - password: ZwovDoOxCo
10. You can submit any defects/suggestions here under the Issues tab. https://github.com/Greenstand/treetracker-ios
11. If all checks ok, please report to the iOS Team

**Comment by Davidezrajay** [comment]
@pranavkparti where should this information live? 
It is here in a wiki in Android, although I'm not sure that is easy to find. If we go that way, it would be here: https://github.com/Greenstand/treetracker-ios/wiki

**Comment by pranavkparti** [comment]
@Davidezrajay This goes in the development documentation for the Treetracker App. We will be migrating away from wikis and other sources to Gitbook completely. I plan to reach out to the different teams to audit the existing documentation soon.

**Comment by CorrWu** [comment]
I just submitted a [pull request](https://github.com/Greenstand/greenstand-documentation/pull/47)
