### ISSUE TITLE
Operations - Grants (Greenstand Operations Handbook) Error

### ISSUE THREAD

**Issue by cynthiabondi** [Greenstand/greenstand-documentation#65]
there is an error for the Handbook, it can not be found here: https://docs.greenstand.org/operations/v/grants/grant-content-and-resources

**Comment by pranavkparti** [comment]
@cynthiabondi Hello, could you elaborate on the issue you're facing? Thank you.

**Comment by cynthiabondi** [comment]
Hi @pranavkparti  there is no link to the Greenstand Operations Handbook.

**Comment by pranavkparti** [comment]
@cynthiabondi Thank you for pointing that out. The Operations handbook link has been added and also published as a part of the Operations collection, so it can be accessed through the dropdown at the top of the operations documentation.

**Comment by Davidezrajay** [comment]
Wonderful Thanks!
